apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/nikhilshah28/demo-app
  newTag: sha256:9d64d964a50d0ac4ec9197f1c3dba3fe22b78ab9360f94ae04b8f5dffbe731f6